import { mkdirSync, writeFileSync } from "node:fs";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const FAMILIES = [
  { css: "Archivo:wdth,wght@62..125,100..900", local: "Archivo" },
  { css: "Source+Sans+3:wght@200..900", local: "SourceSans3" },
  { css: "IBM+Plex+Mono:wght@400;500;600", local: "IBMPlexMono" },
];

mkdirSync("public/fonts", { recursive: true });
let out = "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n";

for (const fam of FAMILIES) {
  const res = await fetch(
    `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`,
    { headers: { "User-Agent": UA } },
  );
  if (!res.ok) throw new Error(`${fam.local}: CSS fetch failed ${res.status}`);
  let css = await res.text();

  const urls = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)]
    .map((m) => m[1]);
  const seen = new Map();

  for (const url of urls) {
    if (seen.has(url)) continue;
    const file = `${fam.local}-${seen.size}.woff2`;
    const bin = await fetch(url, { headers: { "User-Agent": UA } });
    if (!bin.ok) throw new Error(`${file}: download failed ${bin.status}`);
    writeFileSync(`public/fonts/${file}`, Buffer.from(await bin.arrayBuffer()));
    seen.set(url, file);
    console.log(`  ${file}`);
  }

  for (const [url, file] of seen) css = css.replaceAll(url, `/fonts/${file}`);
  out += `\n/* ===== ${fam.local} ===== */\n${css}`;
}

mkdirSync("src/styles", { recursive: true });
writeFileSync("src/styles/fonts.css", out);
console.log("wrote src/styles/fonts.css");
