import { useCallback, useEffect, useRef, useState } from "react";

import { getCheckInQr } from "../../api/checkIns";
import { listLocations } from "../../api/locations";
import { useLanguage } from "../../i18n/LanguageContext";
import { text } from "../../theme";
import type { CheckInQr as CheckInQrData, Location } from "../../types";

/** Poll interval. The code only has to change before the NEXT person scans,
 *  and a stale code is already spent, so it correctly fails rather than
 *  letting someone in twice. */
const POLL_MS = 3000;

export default function CheckInQr() {
  const { t } = useLanguage();
  const [locations, setLocations] = useState<Location[]>([]);
  const [locationId, setLocationId] = useState("");
  const [qr, setQr] = useState<CheckInQrData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const timer = useRef<number | null>(null);

  useEffect(() => {
    listLocations()
      .then((rows) => {
        setLocations(rows);
        if (rows.length > 0) setLocationId(rows[0].id);
      })
      .catch(() => setError(t.checkIn.managerLoadFailed));
  }, [t]);

  const refresh = useCallback(async () => {
    if (!locationId) return;
    try {
      setQr(await getCheckInQr(locationId));
      setError(null);
    } catch {
      setError(t.checkIn.managerLoadFailed);
    }
  }, [locationId, t]);

  useEffect(() => {
    void refresh();
    timer.current = window.setInterval(refresh, POLL_MS);
    return () => {
      if (timer.current !== null) window.clearInterval(timer.current);
    };
  }, [refresh]);

  return (
    <div className="p-6">
      <h1 className={`text-2xl font-semibold mb-1 ${text.body}`}>
        {t.checkIn.qrTitle}
      </h1>
      <p className={`mb-6 max-w-2xl ${text.muted}`}>{t.checkIn.qrDesc}</p>

      <label className={`block mb-2 text-sm ${text.muted}`}>
        {t.checkIn.selectLocation}
      </label>
      <select
        value={locationId}
        onChange={(e) => setLocationId(e.target.value)}
        className="glass-input mb-6"
      >
        {locations.map((l) => (
          <option key={l.id} value={l.id}>
            {l.name}
          </option>
        ))}
      </select>

      {error && <div className="glass-alert-error mb-4">{error}</div>}

      {qr && (
        <div className="flex flex-col items-center">
          <div
            className="bg-white p-4 rounded-xl"
            style={{ width: 320, height: 320 }}
            /* The SVG is generated by our own backend from a value we
               control, never from user input. */
            dangerouslySetInnerHTML={{ __html: qr.svg }}
          />
          <p className={`mt-4 text-sm ${text.muted}`}>
            {t.checkIn.checkedInToday}: {qr.checked_in_today}
          </p>
        </div>
      )}
    </div>
  );
}
